"""Spreadsheets and delimited text, read into `Grid`s.

Cells come back as strings on purpose. "1,5" is one and a half in Europe and
fifteen in a badly exported file; "12 pcs" is a quantity and a unit in one cell.
Deciding that here would throw away what the customer actually wrote, and the
normalization stage - which knows the field it is filling - can still decide it
later. The reader's job is to lose nothing.
"""

import csv
import io
import logging
from datetime import date, datetime, time

import openpyxl
import xlrd
from openpyxl.utils.exceptions import InvalidFileException

from src.infrastructure.documents.budget import Budget
from src.infrastructure.documents.models import (
    PASSWORD_PROTECTED,
    ROWS_TRUNCATED,
    UNREADABLE,
    Document,
    FileKind,
    Grid,
)

logger = logging.getLogger(__name__)

_CSV_ENCODINGS = ("utf-8-sig", "cp1252", "latin-1")


def read_xlsx(document: Document, data: bytes, budget: Budget) -> Document:
    """.xlsx and .xlsm through openpyxl.

    `data_only=True` returns the value Excel last cached for a formula. A file
    generated by a system that never opened it in Excel has no cache, and those
    cells read as empty - which is why the loader flags a sheet that is all
    formulas and no values instead of reporting an empty RFQ.
    """
    try:
        workbook = openpyxl.load_workbook(
            io.BytesIO(data), read_only=True, data_only=True
        )
    except InvalidFileException:
        document.warn(UNREADABLE)
        return document
    except Exception as error:  # noqa: BLE001 - openpyxl raises many unrelated types
        document.warn(PASSWORD_PROTECTED if _looks_encrypted(error) else UNREADABLE)
        logger.debug("openpyxl could not open %s: %s", document.filename, error)
        return document

    try:
        for sheet in workbook.worksheets:
            grid = _grid_from_rows(
                sheet.iter_rows(values_only=True),
                origin=f"{document.origin}#{sheet.title}",
                name=sheet.title,
                budget=budget,
                document=document,
            )
            if not grid.is_empty:
                document.grids.append(grid)
    finally:
        workbook.close()

    return document


def read_xls(document: Document, data: bytes, budget: Budget) -> Document:
    """The legacy binary format, still what many ERP systems export."""
    try:
        book = xlrd.open_workbook(file_contents=data)
    except Exception as error:  # noqa: BLE001 - xlrd raises XLRDError and more
        document.warn(UNREADABLE)
        logger.debug("xlrd could not open %s: %s", document.filename, error)
        return document

    for sheet in book.sheets():
        rows = (sheet.row_values(index) for index in range(sheet.nrows))
        grid = _grid_from_rows(
            rows,
            origin=f"{document.origin}#{sheet.name}",
            name=sheet.name,
            budget=budget,
            document=document,
        )
        if not grid.is_empty:
            document.grids.append(grid)

    return document


def read_csv(document: Document, data: bytes, budget: Budget) -> Document:
    """Delimited text, with the separator sniffed rather than assumed.

    Semicolons are the norm wherever the decimal separator is a comma, which is
    most of the European traffic this mailbox sees.
    """
    text = _decode(data)
    sample = text[:8192]

    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=",;\t|")
        delimiter = dialect.delimiter
    except csv.Error:
        delimiter = ","

    reader = csv.reader(io.StringIO(text), delimiter=delimiter)
    grid = _grid_from_rows(
        reader, origin=document.origin, name=None, budget=budget, document=document
    )
    if not grid.is_empty:
        document.grids.append(grid)

    return document


def read_text(document: Document, data: bytes, _budget: Budget) -> Document:
    document.text = _decode(data)
    return document


def _grid_from_rows(rows, *, origin, name, budget: Budget, document: Document) -> Grid:
    """Materialise an iterator of rows, stopping at the row and column ceilings."""
    collected: list[list[str | None]] = []

    for index, row in enumerate(rows):
        if index >= budget.max_spreadsheet_rows:
            document.warn(ROWS_TRUNCATED)
            document.truncated = True
            break
        collected.append([_cell(value) for value in row[: budget.max_spreadsheet_cols]])

    return Grid(origin=origin, rows=_without_trailing_blanks(collected), name=name)


def _cell(value: object) -> str | None:
    """One cell as the customer would read it.

    Dates go to ISO because every downstream parser understands it. Whole floats
    lose the ".0" Excel stores them with - a quantity of "2.0" that reaches the
    template as text reads as a data-entry mistake to the person checking it.
    """
    if value is None:
        return None
    if isinstance(value, str):
        return value.strip() or None
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, datetime):
        return value.isoformat(sep=" ", timespec="minutes")
    if isinstance(value, (date, time)):
        return value.isoformat()
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _without_trailing_blanks(rows: list[list[str | None]]) -> list[list[str | None]]:
    """Drop the empty rows Excel keeps below the data.

    A sheet the user once scrolled to row 900 reports 900 rows, and 880 of them
    would otherwise reach the model as blank lines.
    """
    while rows and not any(cell for cell in rows[-1]):
        rows.pop()
    return rows


def _decode(data: bytes) -> str:
    for encoding in _CSV_ENCODINGS:
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    # latin-1 maps every byte, so this is only reached if the tuple changes.
    return data.decode("utf-8", "replace")


def _looks_encrypted(error: Exception) -> bool:
    return "encrypt" in str(error).lower() or "password" in str(error).lower()


READERS = {
    FileKind.XLSX: read_xlsx,
    FileKind.XLS: read_xls,
    FileKind.CSV: read_csv,
    FileKind.TEXT: read_text,
}
