"""records, files and rfq lines

Revision ID: b9a56fb6ed53
Revises: 
Create Date: 2026-09-13 22:30:50.558837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9a56fb6ed53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mailbox', sa.String(length=320), nullable=True),
    sa.Column('sender_name', sa.String(length=256), nullable=True),
    sa.Column('sender_address', sa.String(length=320), nullable=True),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body_chars', sa.Integer(), nullable=False),
    sa.Column('body_key', sa.String(length=1024), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('labelled', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('emails_pkey')),
    sa.UniqueConstraint('message_id', name='emails_message_id_key')
    )
    op.create_index('emails_received_at_idx', 'emails', [sa.literal_column('received_at DESC')], unique=False)
    op.create_table('email_deliveries',
    sa.Column('email_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('forwarded_to', sa.String(length=320), nullable=True),
    sa.Column('cc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=True),
    sa.Column('region_rule', sa.String(length=32), nullable=True),
    sa.Column('attached', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('email_deliveries_email_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email_id', name=op.f('email_deliveries_pkey'))
    )
    op.create_table('email_extractions',
    sa.Column('email_id', sa.String(length=64), nullable=False),
    sa.Column('items', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('missing_required', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vessel_name', sa.String(length=256), nullable=True),
    sa.Column('imo', sa.String(length=32), nullable=True),
    sa.Column('delivery_port', sa.String(length=128), nullable=True),
    sa.Column('header', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('email_extractions_email_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email_id', name=op.f('email_extractions_pkey'))
    )
    op.create_table('email_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('ATTACHMENT', 'FORM', name='file_role_enum'), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('saved_as', sa.String(length=256), nullable=True),
    sa.Column('blob_key', sa.String(length=1024), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('email_files_email_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_files_pkey'))
    )
    op.create_index(op.f('email_files_email_id_idx'), 'email_files', ['email_id'], unique=False)
    op.create_table('email_verdicts',
    sa.Column('email_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_rfq', sa.Boolean(), nullable=False),
    sa.Column('requires_action', sa.Boolean(), nullable=False),
    sa.Column('recommended_action', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('decision_path', sa.String(length=32), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('email_verdicts_email_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email_id', name=op.f('email_verdicts_pkey'))
    )
    op.create_index('email_verdicts_is_rfq_idx', 'email_verdicts', ['is_rfq'], unique=False)
    op.create_table('rfq_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('verbatim', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('customer_code', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('uom', sa.String(length=32), nullable=True),
    sa.Column('item_code', sa.String(length=64), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('item', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('how', sa.String(length=32), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('rfq_lines_email_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rfq_lines_pkey')),
    sa.UniqueConstraint('email_id', 'index', name='rfq_lines_email_id_index_key')
    )
    op.create_index(op.f('rfq_lines_email_id_idx'), 'rfq_lines', ['email_id'], unique=False)
    op.create_table('rfq_line_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('item', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['rfq_lines.id'], name=op.f('rfq_line_candidates_line_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rfq_line_candidates_pkey')),
    sa.UniqueConstraint('line_id', 'rank', name='rfq_line_candidates_line_id_rank_key')
    )
    op.create_index(op.f('rfq_line_candidates_line_id_idx'), 'rfq_line_candidates', ['line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('rfq_line_candidates_line_id_idx'), table_name='rfq_line_candidates')
    op.drop_table('rfq_line_candidates')
    op.drop_index(op.f('rfq_lines_email_id_idx'), table_name='rfq_lines')
    op.drop_table('rfq_lines')
    op.drop_index('email_verdicts_is_rfq_idx', table_name='email_verdicts')
    op.drop_table('email_verdicts')
    op.drop_index(op.f('email_files_email_id_idx'), table_name='email_files')
    op.drop_table('email_files')
    op.drop_table('email_extractions')
    op.drop_table('email_deliveries')
    op.drop_index('emails_received_at_idx', table_name='emails')
    op.drop_table('emails')
    # Autogenerate creates the enum type on the way up and forgets it on the
    # way down, so a downgrade leaves it behind and the next upgrade fails with
    # "type file_role_enum already exists". Dropped by hand.
    sa.Enum(name='file_role_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
